In [ ]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\DELL\Desktop\MATHS PROJECTS\PR-5\combined_employee_dataset_1.csv")
df

,age,years_experience,education_level,department,performance_score,performance_category
0,58,23,High School,Finance,10,Excellent
1,48,39,Bachelor,HR,6,Good
2,34,15,High School,HR,5,Average
3,27,29,PhD,HR,4,Average
4,40,36,PhD,Finance,2,Poor
...,...,...,...,...,...,...
786,21,19,Bachelor,Sales,9,Very Good
787,25,4,Master,Finance,4,Average
788,47,35,Bachelor,Finance,6,Good
789,47,17,High School,Sales,1,Poor


In [5]:
employee1 = df.loc[0, ['age','years_experience','performance_score']].values
employee2 = df.loc[1, ['age','years_experience','performance_score']].values

print("Employee 1 Vector :", employee1)
print("Employee 2 Vector :", employee2)

Employee 1 Vector : [np.int64(58) np.int64(23) np.int64(10)]
Employee 2 Vector : [np.int64(48) np.int64(39) np.int64(6)]


In [6]:
norm1 = np.linalg.norm(employee1, ord=1)

print("Norm-1 :", norm1)

Norm-1 : 91


In [7]:
norm2 = np.linalg.norm(employee1)

print("Norm-2 :", norm2)

Norm-2 : 63.190189111918315


In [8]:

dot_product = np.dot(employee1, employee2)

print("Dot Product :", dot_product)

Dot Product : 3741


In [9]:

cos_theta = np.dot(employee1, employee2) / (np.linalg.norm(employee1) * np.linalg.norm(employee2))

angle = np.degrees(np.arccos(cos_theta))

print("Angle Between Vectors :", angle)

Angle Between Vectors : 17.679505521863163


In [11]:

employee1 = df.loc[0, ['age','years_experience','performance_score']].values
employee2 = df.loc[1, ['age','years_experience','performance_score']].values

v1 = employee1[:3]
v2 = employee2[:3]

cross_product = np.cross(v1, v2)

print("Cross Product :", cross_product)

Cross Product : [np.int64(-252) np.int64(132) np.int64(1158)]


In [12]:

projection = (np.dot(employee1, employee2) / np.dot(employee2, employee2)) * employee2

print("Projection :", projection)

Projection : [np.float64(46.50815850815851) np.float64(37.78787878787879)
 np.float64(5.813519813519814)]


In [13]:
A = df[['age','years_experience','performance_score']].head(5).values

print(A)

[[58 23 10]
 [48 39  6]
 [34 15  5]
 [27 29  4]
 [40 36  2]]


In [14]:
B = np.array([
    [1,2,3],
    [5,4,3],
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

addition = A + B

print(addition)

[[59 25 13]
 [53 43  9]
 [35 16  6]
 [29 31  6]
 [43 39  5]]


In [18]:
B = np.array([
    [1,2,3,4],
    [5,4,3,2],
    [1,1,1,1]
])

multiplication = np.matmul(A, B)

print(multiplication)

[[183 218 253 288]
 [249 258 267 276]
 [114 133 152 171]
 [176 174 172 170]
 [222 226 230 234]]


In [19]:

transpose = A.T


print(transpose)

[[58 48 34 27 40]
 [23 39 15 29 36]
 [10  6  5  4  2]]


In [20]:
A = df[['age','years_experience','performance_score']].head(3).values

determinant = np.linalg.det(A)

print("Determinant :", determinant)

Determinant : -797.9999999999995


In [21]:

inverse = np.linalg.inv(A)

print(inverse)

[[-0.13157895 -0.04385965  0.31578947]
 [ 0.04511278  0.06265664 -0.16541353]
 [ 0.7593985   0.11027569 -1.45112782]]


In [22]:

transformation_matrix = np.array([
    [1,0],
    [0,2]
])

points = np.array([
    [2,3],
    [4,5]
])

transformed_points = np.dot(points, transformation_matrix)

print(transformed_points)

[[ 2  6]
 [ 4 10]]


In [23]:

cov_matrix = np.cov(A.T)

print(cov_matrix)

[[145.33333333  61.33333333  29.        ]
 [ 61.33333333 149.33333333   0.        ]
 [ 29.           0.           7.        ]]


In [24]:

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues :")
print(eigenvalues)

print("\nEigenvectors :")
print(eigenvectors)

Eigenvalues :
[ 2.10730699e+02  9.09359674e+01 -3.72153363e-16]

Eigenvectors :
[[-0.7039152  -0.67078598 -0.23355849]
 [-0.70318107  0.7045102   0.09592581]
 [-0.10019865 -0.23175754  0.96759944]]


In [25]:

from scipy.linalg import lu

P, L, U = lu(A)

print("P Matrix :")
print(P)

P Matrix :
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:

U, S, VT = np.linalg.svd(A)

print("U Matrix :")
print(U)

print("\nSingular Values :")
print(S)

print("\nVT Matrix :")
print(VT)

U Matrix :
[[-0.65789852  0.59839597 -0.45726557]
 [-0.64291995 -0.76246739 -0.07278336]
 [-0.39220335  0.2461011   0.88634687]]

Singular Values :
[95.18352967 14.13307426  0.59320451]

VT Matrix :
[[-0.86520416 -0.48420766 -0.1302486 ]
 [ 0.45821372 -0.86899738  0.18677188]
 [ 0.20362207 -0.10191411 -0.97373075]]


In [27]:
from sklearn.decomposition import PCA

X = df[['age','years_experience','performance_score']]

pca = PCA(n_components=2)

pca_result = pca.fit_transform(X)

print(pca_result)

[[17.82280057 -3.91524678]
 [13.48300643 14.40127993]
 [-7.49793903 -3.8288385 ]
 ...
 [11.24939913 10.93599121]
 [ 5.43569988 -6.1665846 ]
 [ 1.43681116  6.91913229]]


In [28]:

pca_df = pd.DataFrame(pca_result, columns=['PC1','PC2'])

pca_df.head()

,PC1,PC2
0,17.822801,-3.915247
1,13.483006,14.401280
2,-7.497939,-3.828839
3,-9.626696,11.665603
4,4.924696,14.086029


In [30]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

X = df[['age','years_experience','performance_score']]

y = df['department']

lda = LinearDiscriminantAnalysis(n_components=1)

lda_result = lda.fit_transform(X, y)

print(lda_result)

[[-1.00420598e+00]
 [-1.41149857e+00]
 [ 5.41861116e-01]
 [-2.67518672e-01]
 [-4.54314913e-01]
 [ 7.91469188e-01]
 [-1.59201582e+00]
 [ 1.99144487e-01]
 [ 4.07281138e-01]
 [-1.27889202e+00]
 [ 2.16820710e+00]
 [ 5.89451122e-01]
 [-4.72719677e-01]
 [-2.44525530e-01]
 [-3.19117930e-01]
 [-9.19806447e-01]
 [ 1.40749092e+00]
 [ 2.92622757e-01]
 [-4.65412212e-02]
 [-1.79724133e+00]
 [-1.79541982e-01]
 [ 1.89146074e+00]
 [ 3.37116713e-01]
 [ 1.41154919e+00]
 [ 1.74411347e+00]
 [-1.22016296e+00]
 [ 1.51234217e+00]
 [ 1.72309377e+00]
 [ 3.89332975e-01]
 [ 4.37539985e-01]
 [-1.90356040e+00]
 [-2.87046052e-01]
 [ 2.75291599e-01]
 [ 1.06058013e+00]
 [-3.07954366e-01]
 [-1.11629843e+00]
 [ 5.99603464e-01]
 [-1.03185458e-01]
 [-1.75731125e+00]
 [ 5.87477688e-01]
 [ 5.30697552e-01]
 [-1.97420593e+00]
 [ 9.74663768e-01]
 [ 1.82239442e+00]
 [ 7.23525489e-01]
 [-7.29457555e-01]
 [ 1.65308484e-01]
 [-2.00184983e+00]
 [-6.81410949e-01]
 [-2.25615155e-01]
 [ 9.50140419e-01]
 [ 3.55570487e-01]
 [ 7.9724256

In [31]:

lda_df = pd.DataFrame(lda_result, columns=['LD1'])

lda_df.head()

,LD1
0,-1.004206
1,-1.411499
2,0.541861
3,-0.267519
4,-0.454315
